### ISSUE TITLE
[Feature Request] New line before '['

### ISSUE THREAD

**Issue by VonDoogles** [sunjw/jstoolnpp#20]
It would be really nice to have a "New line before '['" option.  This option exists for objects, but not arrays.

Ex:

```
{
    "myArray" :
    [
        ...
    ]
}
```

**Comment by sunjw** [comment]
I'll check if this is a common use case.

**Comment by BloodyRain2k** [comment]
I think the issue is more along "new line for [ only happens when 'new line for {' is checked".
That's what I just found out.

Without "new line for {" it does not add new lines for [ on it's own (though it will keep them if they are made manually and the same for all entries of the array) but if "new line for {" is checked it will add new lines to [ on it's own like expected.

I had this with both, 1.16.something and 1.18.0.

**Comment by sunjw** [comment]
Thanks for the comment @BloodyRain2k. I'll do some fix for "new line for {" checked later. It seems buggy in some cases.

**Comment by NudeSpoons** [comment]
@sunjw 
Could you provide an update on your progress on providing this enhancement, please?

**Comment by sunjw** [comment]
Remove "new line before '{'" support.
